# Generated by Django 5.0.2 on 2024-03-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
